import { StyleSheet } from 'react-native';

const lightColors = {
  background: '#F0F2F5',
  text: '#1C1C1E',
  primaryGreen: '#28A745',
  primaryGreenDark: '#1E7E34',
  secondaryBlack: '#343A40',
  border: '#CED4DA',
  inputBackground: '#FFFFFF',
  inputText: '#495057',
  placeholderText: '#6C757D',
  buttonText: '#FFFFFF',
  errorText: '#DC3545',
  loadingOverlayBackground: 'rgba(0, 0, 0, 0.6)',
  loadingIndicator: '#FFFFFF',
  loadingText: '#FFFFFF',
  titleText: '#28A745',
  switchEnabledTrackColor: '#A5D6A7',
  switchEnabledThumbColor: '#28A745',
  switchDisabledTrackColor: '#BDBDBD',
  switchDisabledThumbColor: '#F5F5F5',
  switchIosBgColor: '#E0E0E0',
};

const darkColors = {
  background: '#121212',
  text: '#E0E0E0',
  primaryGreen: '#2ECC71',
  primaryGreenDark: '#27AE60',
  secondaryBlack: '#000000',
  border: '#3A3A3C',
  inputBackground: '#1E1E1E',
  inputText: '#E0E0E0',
  placeholderText: '#757575',
  buttonText: '#FFFFFF',
  errorText: '#FF8A80',
  loadingOverlayBackground: 'rgba(0, 0, 0, 0.7)',
  loadingIndicator: '#2ECC71',
  loadingText: '#E0E0E0',
  titleText: '#2ECC71',
  switchEnabledTrackColor: '#4A7C59',
  switchEnabledThumbColor: '#2ECC71',
  switchDisabledTrackColor: '#424242',
  switchDisabledThumbColor: '#BDBDBD',
  switchIosBgColor: '#333333',
};

const getThemedStyles = (isDarkMode) => {
  const theme = isDarkMode ? darkColors : lightColors;

  return StyleSheet.create({
    keyboardAvoidingContainer: {
      flex: 1,
      backgroundColor: theme.background,
    },
    scrollContainer: {
      paddingHorizontal: 24,
      paddingVertical: 20,
      flexGrow: 1,
    },
    title: {
      fontSize: 28,
      fontWeight: 'bold',
      color: theme.titleText,
      textAlign: 'center',
      marginBottom: 25,
      marginTop: 10,
    },
    label: {
      fontSize: 16,
      fontWeight: '600',
      color: theme.text,
      marginBottom: 10,
    },
    input: {
      backgroundColor: theme.inputBackground,
      color: theme.inputText,
      height: 52,
      borderWidth: 1,
      borderColor: theme.border,
      borderRadius: 10,
      paddingHorizontal: 16,
      marginBottom: 22,
      fontSize: 16,
      shadowColor: theme.secondaryBlack,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDarkMode ? 0.25 : 0.08,
      shadowRadius: 3,
      elevation: isDarkMode ? 2 : 1,
    },
    inputMultiline: {
      height: 100,
      paddingTop: 12,
    },
    placeholderText: {
      color: theme.placeholderText,
    },
    switchContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 25,
      paddingVertical: 10,
    },
    switchEnabledTrack:   { color: theme.switchEnabledTrackColor },
    switchEnabledThumb:   { color: theme.switchEnabledThumbColor },
    switchDisabledTrack:  { color: theme.switchDisabledTrackColor },
    switchDisabledThumb:  { color: theme.switchDisabledThumbColor },
    switchIosBackground:  { color: theme.switchIosBgColor },
    button: {
      backgroundColor: theme.primaryGreen,
      height: 52,
      borderRadius: 26,
      justifyContent: "center",
      alignItems: "center",
      marginTop: 15,
      marginBottom: 20,
      shadowColor: theme.primaryGreen,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDarkMode ? 0.4 : 0.3,
      shadowRadius: 5,
      elevation: 6,
    },
    buttonDisabled: {
      backgroundColor: theme.border,
      elevation: 0,
      shadowOpacity: 0,
    },
    buttonText: {
      color: theme.buttonText,
      fontSize: 17,
      fontWeight: "bold",
    },
    loadingOverlay: {},
    loadingIndicator: { color: theme.loadingIndicator },
    loadingText: {},
    errorText: {},
  });
};

export default getThemedStyles;
