import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

const getThemedStyles = (isDarkMode) => {
  const theme = isDarkMode
    ? {
        background: '#121212',
        text: '#E0E0E0',
        primaryGreen: '#2ECC71',
        card: '#1E1E1E',
        borderColor: '#333333',
        carouselPlaceholderBg: '#1A1A1A',
        errorText: '#FF8A80',
        retryButtonCarouselBg: '#2ECC71',
        retryButtonCarouselText: '#121212',
        secondaryText: '#BBBBBB',
        iconColor: '#E0E0E0',
        placeholderIconColor: '#777777',
        paginationDotActive: '#2ECC71',
        paginationDotInactive: '#555555',
        carouselTitleOverlayBg: 'rgba(0, 0, 0, 0.6)',
      }
    : {
        background: '#F0F2F5',
        text: '#1C1C1E',
        primaryGreen: '#28A745',
        card: '#FFFFFF',
        borderColor: '#DDDDDD',
        carouselPlaceholderBg: '#E9E9E9',
        errorText: '#D32F2F',
        retryButtonCarouselBg: '#28A745',
        retryButtonCarouselText: '#FFFFFF',
        secondaryText: '#666666',
        iconColor: '#1C1C1E',
        placeholderIconColor: '#AAAAAA',
        paginationDotActive: '#28A745',
        paginationDotInactive: '#CCCCCC',
        carouselTitleOverlayBg: 'rgba(0, 0, 0, 0.5)',
      };

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    scrollViewContent: {
      paddingBottom: 40,
      paddingHorizontal: 0,
    },
    welcomeText: {
      fontSize: 28,
      fontWeight: 'bold',
      color: theme.primaryGreen,
      textAlign: 'center',
      marginHorizontal: 16,
      marginTop: 20,
      marginBottom: 20,
    },
    sectionTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: theme.text,
      marginTop: 30,
      marginBottom: 16,
      paddingHorizontal: 16,
    },
    carouselContainer: {
      paddingLeft: 16,
      paddingRight: (screenWidth - (screenWidth * 0.7 + 16)) - 16,
      paddingVertical: 10,
    },
    carouselItem: {
      width: screenWidth * 0.7,
      height: screenWidth * 0.45,
      marginRight: 16,
      borderRadius: 12,
      overflow: 'hidden',
      backgroundColor: theme.borderColor,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: isDarkMode ? 0.3 : 0.15,
      shadowRadius: 5,
      elevation: 5,
    },
    carouselImage: {
      width: '100%',
      height: '100%',
    },
    carouselTitleOverlay: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      backgroundColor: theme.carouselTitleOverlayBg,
      paddingVertical: 8,
      paddingHorizontal: 10,
    },
    carouselItemTitle: {
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '600',
      textAlign: 'center',
    },
    carouselLoadingContainer: {
      height: screenWidth * 0.45 + 20,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingIndicatorCarousel: {
      color: theme.primaryGreen,
    },
    carouselErrorContainer: {
      height: screenWidth * 0.45 + 20,
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: 16,
      padding: 10,
      backgroundColor: theme.card,
      borderRadius: 10,
    },
    errorTextCarousel: {},
    retryButtonCarousel: {},
    retryButtonTextCarousel: {},
    carouselPlaceholder: {
      height: screenWidth * 0.45 + 20,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.carouselPlaceholderBg,
      borderRadius: 10,
      marginHorizontal: 16,
      padding: 10,
    },
    emptyCarouselText: {},
    paginationContainer: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 12,
      marginBottom: 10,
    },
    paginationDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      marginHorizontal: 4,
    },
    paginationDotActive: {
      backgroundColor: theme.paginationDotActive,
      width: 10,
      height: 10,
      borderRadius: 5,
    },
    paginationDotInactive: {
      backgroundColor: theme.paginationDotInactive,
    },
    placeholderContainer: {
      backgroundColor: theme.card,
      borderRadius: 12,
      paddingVertical: 40,
      paddingHorizontal: 20,
      marginHorizontal: 16,
      marginBottom: 24,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: isDarkMode ? 0.2 : 0.08,
      shadowRadius: 3,
      elevation: 2,
    },
    placeholderText: {
      fontSize: 16,
      fontStyle: 'italic',
      textAlign: 'center',
      color: theme.secondaryText,
      paddingHorizontal: 10,
    },
    placeholderIcon: {
      color: theme.placeholderIconColor,
    },
    actionButton: {
      backgroundColor: theme.primaryGreen,
      paddingVertical: 14,
      paddingHorizontal: 24,
      borderRadius: 25,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 20,
      marginHorizontal: 16,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: isDarkMode ? 0.3 : 0.15,
      shadowRadius: 4,
      elevation: 4,
    },
    actionButtonText: {},
  });
};

export default getThemedStyles;
